baseurl = "http://go.programmingandlife.com/"
languageCode = "en-us"
title = "Learning Go: A C Programmer's Perspective"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/howardplus"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/hctw6"

[params]
    description = "Learning Go: A C Programmer's Perspective"

    [params.logo]
    url = "logo_hc.png"
    width = 50
    height = 50
    alt = "Logo"

